# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d19336d0bb40adadbc289e4ffecc8fdba8b5c77a5ab8420c3759a7de36d92db6abc259d6e9b0df2be429bfbc3d16cf017bff9c5026139f631e1f6a9f3cccd6

test:
  secret_key_base: 1b3ead98986ee6846d22a03b8e1d32c99013aef9f5245db54aca2376abe7b5477039f50fc5285cf1f0a424fc20fd930cbd4c91e0d26c8e6363b9d1c17821787b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
